#!/usr/bin/env node

import { spawn } from "node:child_process";
import { access, cp, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";

const packageDirectory = path.dirname(fileURLToPath(import.meta.url));
const templatesDirectory = path.resolve(packageDirectory, "../templates");
const args = process.argv.slice(2);
const projectArgument = args.find((argument) => !argument.startsWith("-"));
const skipInstall = args.includes("--no-install");
const nonInteractive = args.includes("--yes");

const environmentExample = `PORT=5000
MONGODB_URI=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
JWT_SECRET=
EMAIL_USER=
EMAIL_APP_PASSWORD=
FRONTEND_URL=http://localhost:5173
BACKEND_URL=http://localhost:5000
`;

const gitignore = `node_modules/
.env
.env.*
!.env.example
dist/
frontend/public/bundle.js
frontend/public/bundle.js.map
frontend/public/bundle.css
frontend/public/bundle.css.map
`;

const brandingSource = (projectName) => `export const authBranding = {
  applicationName: ${JSON.stringify(projectName)},
  brandName: ${JSON.stringify(projectName)},
  logoText: ${JSON.stringify(projectName)},
  showPromoPanel: true,
} as const;
`;

const projectReadme = (projectName) => `# ${projectName}

An authentication-ready React and Express project generated by auth12.

## Included

- MongoDB and Mongoose
- Email/password login and signup
- Email OTP verification, expiration, attempt limits, and resend support
- Google OAuth
- Forgot-password and reset-password flows
- JWT HTTP-only authentication cookies, logout, and a protected success page

## Setup

1. Copy \`.env.example\` to \`.env\` and provide your MongoDB, email, Google OAuth, and JWT values.
2. Install dependencies if they were not installed during generation.

\`\`\`bash
cd backend && npm install
cd ../frontend && npm install
\`\`\`

3. Start the services in separate terminals.

\`\`\`bash
cd backend
npm run dev
\`\`\`

\`\`\`bash
cd frontend
npm run dev
\`\`\`

Frontend: http://localhost:5173  
Backend: http://localhost:5000

## Branding

Edit \`frontend/src/config/branding.ts\` to change the application name, brand name, logo text, or promotional panel.
`;

const run = (command, commandArgs, cwd) =>
  new Promise((resolve, reject) => {
    const windows = process.platform === "win32";
    const executable = windows ? process.env.ComSpec || "cmd.exe" : command;
    const executableArgs = windows ? ["/d", "/s", "/c", `${command} ${commandArgs.join(" ")}`] : commandArgs;
    const child = spawn(executable, executableArgs, {
      cwd,
      stdio: "inherit",
    });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${commandArgs.join(" ")} exited with code ${code}.`));
    });
  });

const exists = async (directory) => {
  try {
    await access(directory);
    return true;
  } catch {
    return false;
  }
};

const assertProjectName = (name) => {
  if (!name || !/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(name)) {
    throw new Error("Use a project name containing only letters, numbers, dots, underscores, or hyphens.");
  }
};

const promptForProjectName = async () => {
  if (projectArgument) return projectArgument;
  if (nonInteractive) {
    throw new Error("Provide a project name with --yes, for example: auth12 my-project --yes");
  }

  const prompt = createInterface({ input: process.stdin, output: process.stdout });
  try {
    return (await prompt.question("? Project name: ")).trim();
  } finally {
    prompt.close();
  }
};

const promptForInstall = async () => {
  if (skipInstall) return false;
  if (nonInteractive) return true;

  const prompt = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = (await prompt.question("? Install dependencies? (Y/n): ")).trim().toLowerCase();
    return answer === "" || answer === "y" || answer === "yes";
  } finally {
    prompt.close();
  }
};

const createProject = async () => {
  console.log("\nAuthentication Setup\n");
  const projectName = await promptForProjectName();
  assertProjectName(projectName);
  const installDependencies = await promptForInstall();
  const projectDirectory = path.resolve(process.cwd(), projectName);

  if (await exists(projectDirectory)) {
    throw new Error(`The directory ${projectName} already exists.`);
  }

  console.log("\nDatabase: MongoDB");
  console.log("Authentication: Email & Password, Email OTP, Google OAuth");
  console.log("Forgot Password: Yes\n");
  console.log("Creating project...\n");

  await mkdir(projectDirectory, { recursive: false });
  await Promise.all([
    cp(path.join(templatesDirectory, "frontend"), path.join(projectDirectory, "frontend"), { recursive: true }),
    cp(path.join(templatesDirectory, "backend"), path.join(projectDirectory, "backend"), { recursive: true }),
  ]);

  await mkdir(path.join(projectDirectory, "frontend", "src", "config"), { recursive: true });
  await Promise.all([
    writeFile(path.join(projectDirectory, ".env.example"), environmentExample, "utf8"),
    writeFile(path.join(projectDirectory, ".gitignore"), gitignore, "utf8"),
    writeFile(path.join(projectDirectory, "README.md"), projectReadme(projectName), "utf8"),
    writeFile(path.join(projectDirectory, "frontend", "src", "config", "branding.ts"), brandingSource(projectName), "utf8"),
  ]);

  console.log("✓ Project created");
  console.log("✓ Frontend configured");
  console.log("✓ Backend configured");
  console.log("✓ Authentication configured");
  console.log("✓ MongoDB configured");
  console.log("✓ Environment template created");

  if (installDependencies) {
    await run("npm", ["install"], path.join(projectDirectory, "backend"));
    await run("npm", ["install"], path.join(projectDirectory, "frontend"));
    console.log("✓ Dependencies installed");
  }

  console.log(`\nAuthentication setup complete.\n\nNext steps:\n\ncd ${projectName}\n\nStart backend:\ncd backend\nnpm run dev\n\nStart frontend:\ncd frontend\nnpm run dev\n\nFrontend: http://localhost:5173\nBackend: http://localhost:5000`);
};

createProject().catch((error) => {
  console.error(`\nError: ${error.message}`);
  process.exitCode = 1;
});
